name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install and setup language pack
      run: |
        sudo apt-get install language-pack-de
        sudo locale-gen
        sudo update-locale
        sudo dpkg-reconfigure locales

    - name: run command
      run: locale -a

    - name: run special
      run: sudo update-locale LANG=de_DE.UTF-8 LANGUAGE= LC_MESSAGES= LC_COLLATE= LC_CTYPE=

    - name: install coverage tool
      run: |
        sudo apt-get update
        sudo apt-get install -y gcovr
    - name: setup cmake
      run: sudo apt install cmake
    - name: setup and run linter
      run: |
        pip install cpplint
        cpplint  --filter=-legal,-build/c++11 --linelength=100 *.cpp *.h

    - name: build
      run: |
        cmake -S . -B build
        cmake --build build
      
    - name: run
      run: build/test-monitor

    - name: collect coverage
      run: gcovr --gcov-exclude=".*test.*" -r . --html --html-details -o coverage.html --print-summary

    - name: create coverage artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage
        path: ./*.html
        retention-days: 21
